kind: Service
apiVersion: v1
metadata:
  name: openresty
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 32126
    - port: 443
      protocol: TCP
      name: https
      nodePort: 32127
    - port: 26379
      protocol: TCP
      name: redis
      nodePort: 32128
  type: NodePort
  selector:
    component: openresty