apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-proxy
    role: proxy
  name: redis-proxy
spec:
  containers:
  - name: proxy
    image: 172.16.9.3:5000/kubernetes/redis-proxy:v1
    ports:
    - containerPort: 6379
      name: api
