apiVersion: v1
kind: ReplicationController
metadata:
  # namespace: kube-system
  name: consul-ui
spec:
  replicas: 1
  selector:
    app: consul-ui
  template:
    metadata:
      labels:
        app: consul-ui
    spec:
      containers:
        - name: consul-ui
          securityContext:
            privileged: true
          command: ["/bin/consul", "agent","-ui","-client=0.0.0.0","-config-dir=/config","-ui-dir=/ui","-data-dir=/data","-join=consul"]
          image: 172.16.9.3:5000/guoxf/consul-ui:0.6
          imagePullPolicy: Always
          ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 443
            name: https-port
          - containerPort: 8080
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server
          volumeMounts:
          - mountPath: /config
            name: consul-ui
          - mountPath: /data
            name: consul-ui
      volumes:
        - glusterfs:
            endpoints: glusterfs-cluster
            path: k8s-consul-ui
            readOnly: false
          name: consul-ui