---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: kube-system
  labels:
    name: registry-ui
spec:
  ports:
    # the port that this service should serve on
    - name: http
      port: 8080
  type: NodePort
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: registry-ui